apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"  # Specify Ingress class
spec:
  rules:
    - host: saay.depi.com  # Ensure this matches your intended host
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front-clusterip-service  # Ensure this matches your ClusterIP service
                port:
                  number: 3000  # Should match the frontend service port
