apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: ingress-nginx
spec:
  ingressClassName: nginx  # Use the new field instead of annotation
  rules:
    - host: saay.depi.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front-clusterip-service
                port:
                  number: 3000

